# image_processing.ipynb
# Automatically generated by Colaboratory.
# Original file is located at
# https://colab.research.google.com/drive/1VXp_VGdWLHIVw2v6hfUVaD449ufvV9m7

import cv2
import numpy as np 
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt

img = cv2.imread("/content/Dog.png")

plt.imshow(img)

type(img)

img.shape

cv2_imshow(img)

img_gray  =  cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2_imshow(img_gray)

re_image = cv2.resize(img_gray,(300,400))  # Resize the image

#cv2_imshow(re_img)
#img [: , : , 0 ] = 0          # 0  ----->  Blue
#img [: , : , 1] = 0           # 1 ------> Green
#img [: , : , 2] = 0           # 2 ------> Red

imgBlue = img[ : , : , 0 ]        
imgGreen = img[ : , : , 1]            
imgRed = img[ : , : , 2]

new_img = np.hstack((imgBlue, imgGreen, imgRed))

cv2_imshow(new_img)

re_img = cv2.resize(img,(256,256))

cv2_imshow(re_img)

img_flip = cv2.flip(img, -1)
cv2_imshow(img_flip)

img_crop = img[0:200, 0:300]
cv2_imshow(img_crop)